[project]
name = "lalonde"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dowhy>=0.14",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
]
